# Generated by Django 4.0 on 2022-02-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_repair_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('participants', models.ManyToManyField(blank=True, to='car.Repair')),
            ],
        ),
    ]
